core/urls.py
from django.urls import path
from . import views

app_name = "core"
urlpatterns =[
    path('', views.index, name='index'),
]

ecommercebas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('userauth.urls')),
]

if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauth/urls.py
from django.urls import path
from userauth import views

app_name = 'userauth'

urlpatterns = [
    path('sign-up/',views.register_view, name='sign-up'),
    path('sign-in/',views.login_view, name='sign-in'),
    path('sign-out/',views.logout_view, name='sign-out'),
]

userauth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User (AbstractUser):
    email = models.EmailField(unique=True,null=False)
    username = models.CharField(max_length=100)
    bio = models.CharField(max_length=100)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username
    

userauth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauth.models import User

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'username'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder':'email'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Confirm Password'}))
    class Meta:
        model = User
        fields = ['username', 'email']

userauth/views.py
from django.shortcuts import render,redirect
from userauth.forms import UserRegisterForm
from django.contrib.auth import login, authenticate,logout
from django.contrib import messages
from django.conf import settings
from userauth.models import User

#User = settings.AUTH_USER_MODEL

def register_view(request):
    if request.method == 'POST':
         form = UserRegisterForm(request.POST or None)
         if form.is_valid():
              new_user = form.save()
              username = form.cleaned_data.get('username')
              messages.success(request, f'Hey {username}, Your account was created sucessfuly')
              new_user = authenticate(username=form.cleaned_data['email'], password = form.cleaned_data['password1'])
              login(request, new_user)
              return redirect('core:index')

    else:
         form = UserRegisterForm()
        
   

    context ={
       'form': form,
    }
    return render(request, 'userauth/sign-up.html', context)

def login_view(request):
     if request.user.is_authenticated:
          return redirect ('core:index')
     if request.method == 'POST':
          email = request.POST.get('email')
          password = request.POST.get('password')

          try:
               user =User.objects.get(email=email)
               user = authenticate(request, email=email, password=password)     
               if user is not  None:
                  login(request, user)
                  messages.success(request,'You are logged in.' )
                  return redirect('core:index')
               else:
                   messages.success(request, 'User Does Not Exist. Create an Account')

          except:
               messages.warning(request, f"User with {email} does not exist")

         
     context ={

     }          

     return render(request, 'userauth/sign-in.html', context)         

def  logout_view(request):
     logout(request)
     return redirect('userauth:sign-in')

templates/userauth/sign-in.html
{% extends 'partials/base.html' %}
{% block content %}
{% load static %}

<body class="container text-center">
    <div class="border border-primary mb-6">
        <div class="row justify-content-center ">
            <form class="form-signin" method="POST">
                {% csrf_token %}
                <img class="mb-4" src="{% static 'img/logo.png' %}" alt="" width="72" height="72">
                <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
                <label for="inputEmail" class="sr-only mb-3">Email address</label>
                <input type="email" required name="email" class="form-control mb-3" placeholder="Email address" required
                    autofocus>
                <label for="inputPassword" class="sr-only mb-3">Password</label>
                <input required type="password" name="password" class="form-control mb-3" placeholder="Password"
                    required>
                <div class="checkbox mb-3">
                    <label>
                        <input type="checkbox" value="remember-me"> Remember me
                    </label>
                </div>
                <button class="btn btn-lg btn-primary btn-block mb-6" type="submit">Sign in</button>

                <span class="boarder-primary mt-3 mb-3">Not a User <a
                        href="{% url 'userauth:sign-up' %}">Sign-Up</a></span>
            </form>
        </div>
    </div>
</body>
{% endblock content %}

templates/userauth/sign-up.html
{% extends 'partials/base.html' %}
{% block content %}
{% load static %}
<div class="page-content">
  <div class="container-fluid">
    <div class="row justify-content-center">
      {% if form.errors%}

      <div class="alert alert-danger" role="alert">
        {{ forms.errors }}
      </div>
      {% endif %}
      <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
          {{ form.username }}
        </div>
        <div class="form-group">
          {{ form.email }}
        </div>
        <div class="form-group">
          {{ form.password1 }}
        </div>
        <div class="form-group">
          {{ form.password2 }}
        </div>


        <button type="submit" class="btn btn-primary">Register</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}